pipeline {
    agent none
    options {
        timestamps()
        buildDiscarder(logRotator(numToKeepStr: '10', artifactNumToKeepStr: '10'))
    }
    environment {
        GENERIC_CI_GIT_BRANCH = 'ci_version-2.3'
        MAIN_NODE = 'hpc-test-node-gpu'
    }
    parameters {
        string(name: 'JSON_FILE', description: 'path of json file', defaultValue: 'build/build_configuration.json')
    }
    stages {
        stage("Init Flow") {
            agent { label "${MAIN_NODE}" }
            steps {
                script {
                    library changelog: false, identifier: "ngci@$GENERIC_CI_GIT_BRANCH"
                    LoadNGCI()
                }
            }
        }

    }
}
